import { defineConfig, presetAttributify, presetIcons, presetTypography, presetUno, transformerDirectives, transformerVariantGroup } from 'unocss'

export default defineConfig({
  presets: [
    presetUno({ preflight: false }),
    presetAttributify(),
    presetIcons({
      scale: 1.2,
      warn: true,
      collections: {
        'ci': () => import('@iconify-json/ci/icons.json').then(i => i.default),
        'svg-spinners': () => import('@iconify-json/svg-spinners/icons.json').then(i => i.default),
        'simple-line-icons': () => import('@iconify-json/simple-line-icons/icons.json').then(i => i.default),
      },
    }),
    presetTypography(),
  ],
  transformers: [transformerVariantGroup(), transformerDirectives()],
  shortcuts: [
    {
      'fcc': 'flex justify-center items-center',
      'single-hidden': 'overflow-hidden text-ellipsis whitespace-nowrap',
      'btn-primary-disabled': 'opacity-[0.4] cursor-auto btn-primary',
      'btn-success-disabled': 'opacity-[0.4] cursor-auto btn-success',
      'btn-warning-disabled': 'opacity-[0.4] cursor-auto btn-warning',
      'btn-error-disabled': 'opacity-[0.4] cursor-auto btn-error',
      'btn-base-disabled': 'opacity-[0.4] cursor-auto btn-base',
      'btn-common': 'fcc py-5px px-10px rounded-2px font-bold outline-none',
      'btn-base': 'btn-common text-[#444444] bg-[#F3F3F3] border-1px border-[#DADADA] border-solid',
      'btn-base-hover': 'border-1px border-solid border-[#C6C6C6] btn-base-hover-shadow text-[#333333] bg-[#F7F7F7]',
      'btn-base-active': 'border-1px border-solid border-[#C6C6C6] btn-base-active-shadow',
      'btn-primary': 'btn-common text-white border-1px border-solid border-[#3079ED] bg-[#4C8FFB]',
      'btn-primary-hover': 'border-1px border-solid border-[#2F5BB7] bg-[#3F83F1] btn-primary-hover-shadow',
      'btn-primary-active': 'btn-primary-active-shadow',
      'btn-warning': 'btn-common text-white border-1px border-solid border-[#FB8F3D] btn-warning-bg',
      'btn-warning-hover': 'border-1px border-solid border-[#EB5200] btn-warning-hover-bg btn-warning-hover-shadow',
      'btn-warning-active': 'btn-warning-active-shadow',
      'btn-error': 'btn-common text-white border-1px border-solid border-[#DD4B39] btn-error-bg btn-error-textShadow',
      'btn-error-hover': 'border-1px border-solid border-[#AF301F] btn-error-hover-bg',
      'btn-error-active': 'btn-error-active-shadow btn-error-active-bg',
      'btn-success': 'btn-common text-white border-1px border-solid border-[#0f9d58] bg-[#33b679]',
      'btn-success-hover': 'border-1px border-solid border-[#2ea66e] bg-[#2a9664]',
      'btn-success-active': 'btn-warning-active-shadow',
    },
  ],
  rules: [
    ['btn-base-hover-shadow', { boxShadow: '1px 1px 1px #EAEAEA' }],
    ['btn-base-active-shadow', { boxShadow: 'inset 1px 1px 1px #DFDFDF' }],
    ['btn-primary-shadow', { boxShadow: 'inset 0 1px 0 #80B0FB' }],
    ['btn-primary-hover-shadow', { boxShadow: 'inset 0 1px 0 #5A94F1' }],
    ['btn-primary-active-shadow', { boxShadow: 'inset 0 2px 5px #2370FE' }],
    ['btn-warning-bg', { background: '-webkit-linear-gradient(top, #FDA251, #FB8F3D)' }],
    ['btn-warning-hover-bg', { background: '-webkit-linear-gradient(top, #FD924C, #F9760B)' }],
    ['btn-warning-hover-shadow', { boxShadow: '0 1px #EFEFEF' }],
    ['btn-warning-active-shadow', { boxShadow: 'inset 0 1px 1px rgba(0,0,0,0.3)' }],
    ['btn-error-bg', { background: '-webkit-linear-gradient(top, #DD4B39, #D14836)' }],
    ['btn-error-hover-bg', { background: '-webkit-linear-gradient(top, #DD4B39, #C53727)' }],
    ['btn-error-textShadow', { textShadow: '0 1px 0 #C04131' }],
    ['btn-error-active-shadow', { boxShadow: 'inset 0 1px 1px rgba(0,0,0,0.2)' }],
    ['btn-error-active-bg', { background: '-webkit-linear-gradient(top, #D74736, #AD2719)' }],
  ],
})
